# Build stage
FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npx ng build

#stage2:Ngnix

# Serve using nginx
FROM nginx:alpine

COPY --from=0 /app/dist/angular-15-crud /usr/share/nginx/html

EXPOSE 80	
